### Numpy Intro

### how to use

In [2]:
import numpy as np

In [4]:
# how it looks like?

In [6]:
a=np.arange(6)
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [7]:
# in terms of list we see
list=[3,6,9,12]
print(list)
print(type(list))

[3, 6, 9, 12]
<class 'list'>


### what is an array
* an array is a central data structure of the numpy library.
* an array is a grid of values and it contains information about the raw data, how to locate an element and how to interpret an element.
* it has a grid of elements that can be indexed in various ways.
* the elements are all of the same type, referred to as the array dtype.
* an array can be indexed by a tuple of non-negative integers, by booleans by another array or by integers.

In [9]:
# what is the rank of an array? rank of the array is the no of dimensions.

In [12]:
#what is the shape of an array?
#The shape of the array is a tuple of integers giving the size of the array along each dimensions.

In [13]:
# lets take an example of array
a=np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [14]:
type(a)

numpy.ndarray

In [16]:
#list of lists
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [17]:
# A vector is an array with a single dimension
# there is no difference between row and column vectors


In [18]:
#A matrix refers to an array with 2 dimensions.

In [19]:
len(a)

6

In [20]:
b[0]

array([5, 5, 5])

In [21]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
# 3-D or higher

In [24]:
# for 3d or higher dimension arrays, the term tensor is also commonly used.


In [25]:
# array attributes
#dimensions are called axis.
# c=np.array([[5,5,5],[5,5,5]])
#array([[5,5,5],
 #       [5,5,5]])
    
# 2-axis first axis has length=2
# second axis has length=3

### another example to create an array

In [27]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [28]:
b=np.zeros(2)
b

array([0., 0.])

In [29]:
c=np.ones(3)
c

array([1., 1., 1.])

In [30]:
#create an empty array with 2 elements
d=np.empty(3)
d

array([1., 1., 1.])

### another example to create array

In [32]:
# with range of elements
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [33]:
# with specific range of elements
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [34]:
#continue..
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
#linearly spaced arrays
h=np.linspace(0,10,num=5) #gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#specific data types in array
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [37]:
j=np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

###2-d arrays

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [41]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3-D array

In [43]:
# making and reshaping a 3d array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Array Manipulation
* Reshaping
* Array Flattening
* Dimension shuffling
* joining arrays
* splitting arrays
* add/remove elements to array


# Reshaping 
# reshape()
    # numpy.reshape(array, shape, order)
    # returns: ndarray with mentioned shape
    # returned ndarray elements may be copy of original elements or view of original array elements.
    
# resize()

In [45]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a=np.reshape(a,(5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
c=np.reshape(a,(5,2),order="F")
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
# while doing reshape check the size of the elements
# if size is 10 then your product must be 10 
# reshape donot change the elements but only dimension

In [53]:
a.size

10

In [54]:
np.reshape(a,(4,3))

ValueError: cannot reshape array of size 10 into shape (4,3)

In [55]:
# so directly we can use a=np.reshape(shape, order)

In [56]:
# Resize: this function will change the data of array.
# can mention any size
# numpy.resize(array name, shape)

a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 4, 0]])

In [58]:
# see upper the size is 5 and resize can be done in this too.
# in output we can see the zero(0) as extra added elements


In [59]:
np.resize(a,(5,2))

array([[0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4]])

In [60]:
# above we can see 0,1,2,3,4 after again repeated elements are seen
# that means data is manipulated with the help of resize.


In [64]:
b=np.arange(5)
b.resize((5,2))
b

array([[0, 1],
       [2, 3],
       [4, 0],
       [0, 0],
       [0, 0]])

In [66]:
# to know more about reshape and resize function use 
#help(np.reshape)
#which shows with examples too.
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [67]:
# this is how we can change the shape and size of the array


### Flattening numpy arrays
* flatten method
* ravel method

In [68]:
# flatten: collapsing 2d , 3d , 4d array into 1d array
# ndarray.flatten(order can be C=row A F=col K) usually we use c and F.
e=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])
e


array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [69]:
e.flatten()

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
# here in above we can see collapsing of 3d into 1d without disturbing the elements.

In [71]:
e.flatten(order="F")

array([ 1,  6,  3,  9,  2,  7,  4, 10,  3,  8,  5, 11])

In [72]:
#above see the difference its col wise.


In [73]:
# ravel: in ravel it gives the view.
e.ravel()

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Transpose and Swapaxes
* transpose
* swapaxes

In [75]:
# transpose
# numpy.transpose(array, axes=None)
array1=np.arange(1,11).reshape(5,2)
array1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [76]:
np.transpose(array1)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [77]:
array1.shape

(5, 2)

In [78]:
np.transpose(array1).shape

(2, 5)

In [3]:
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [4]:
np.transpose(a)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [5]:
a.shape

(2, 3, 4)

In [7]:
np.transpose(a).shape

(4, 3, 2)

In [8]:
# swapaxes() : you can interchange any two axis of a given array.
# numpy.swapaxes(array,axis1,axis2)

### splitting and joining in numpy

In [10]:
# Concatenate
# numpy.concatenate(arrays,axis=0,out=None)
a=np.arange(1,5)
b=np.arange(6)
np.concatenate((a,b))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])