### Numpy

### for using Numpy we need to import the libraries as import numpy as np

In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
np.ndim(a)
#ndim is used to check dimension of array

1

In [7]:
print(a.dtype)
#to check the datatype of array in numpy

int32


In [10]:
b=np.array(5)
c=np.array(6.5)
print(b)
print(c)
print(np.ndim(b))
print(np.ndim(c))
#here the dimension will be zero

5
6.5
0
0


In [11]:
a=[[1,2,3],[5,6,7]]
A=np.array(a)
print(A)
np.ndim(A)

[[1 2 3]
 [5 6 7]]


2

In [12]:
# ndim shows 2 dimensional array

In [13]:
a=[[1,2,4],[8,9,7],[4,9,3]]
B=np.array(a)
print(B)
np.ndim(A)

[[1 2 4]
 [8 9 7]
 [4 9 3]]


2

In [14]:
d=[[[6,4,3],[5,3,1],[8,3,6],[9,8,4]]]
D=np.array(d)
print(D)
np.ndim(D)

[[[6 4 3]
  [5 3 1]
  [8 3 6]
  [9 8 4]]]


3

### Shaping

In [16]:
x=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
np.shape(x)

(3, 3)

In [18]:
# here (3,3) means 3 rows and 3 columns

In [19]:
y=np.array([[[1],[2]],
            [[3],[4]],
           [[5],[6]]])
print(y)


[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [20]:
np.shape(y)

(3, 2, 1)

In [21]:
e=np.array([1,2,3,4,5])
np.shape(e)

(5,)

In [22]:
d=np.array(7)
np.shape(d)

()

In [25]:
e.shape=(5,1)
print(e)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [26]:
# here using e.shape=(5,1) previously it has 5 row and no columns and now it has got 5 rows and 1 columns


In [27]:
print(y)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [28]:
y.shape=(6,1)
print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Reshaping

In [33]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### arange

In [45]:
# here arange means the value range
c=np.arange(20).reshape(4,5)
print(c)b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [47]:
a=np.arange(10,20)
a
# here arange(10,20) means starting point is 10 and last end point is 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
a=np.arange(10,20,5)
a

array([10, 15])

### Zeros

In [39]:
a=np.zeros((1,2))
print(a)

[[0. 0.]]


In [40]:
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Full

In [44]:
x=np.full((2,2),10)
print(x)

[[10 10]
 [10 10]]


### Random Integer

In [52]:
x=np.random.randint(1,100,5)
x
# here random.randint will print different set of value everytime

array([38,  2, 64, 41, 66])