### Joining arrays in numpy
 * vstack
 * hstack
 * column_stack

### vstack()


In [3]:
import numpy as np
x=np.array([10,20,30])
y=np.array([40,50,60])
np.stack((x,y))

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
# if only stack is given vertical stack is default 

In [5]:
np.vstack((x,y))

array([[10, 20, 30],
       [40, 50, 60]])

### hstack()
* hstack() will align all the elements horizontally

In [7]:
np.hstack((x,y))

array([10, 20, 30, 40, 50, 60])

### column_stack() it will align all the elements first x as column and second y as second column

In [9]:
np.column_stack((x,y))

array([[10, 40],
       [20, 50],
       [30, 60]])

### Intersect and difference
* intersect means it is setting intersection between two sets
* difference means it is setting difference by excluding the common elements


### Intersect

In [13]:
x=np.array([10,20,30,40,50,60])
y=np.array([50,60,70,80,90,100])
np.intersect1d(x,y)
# here intersect1d means 1d is one dimensional

array([50, 60])

### Difference 

In [15]:
np.setdiff1d(x,y)

array([10, 20, 30, 40])

In [16]:
np.setdiff1d(y,x)

array([ 70,  80,  90, 100])

In [17]:
# here in first one it prints only x and then in second y excluding common elements on both.