### Numpy Mathematics

### Addition sum



In [5]:
import numpy as np
x=np.array([10,20])
y=np.array([30,40])
np.sum([x,y])

100

### using axis=0 and axis=1

In [6]:
np.sum([x,y],axis=0)

array([40, 60])

### axis=1 is little confusing hence it should be practised more and more

In [8]:
np.sum([x,y],axis=1)

array([30, 70])

### Addition subtraction multiplication division

In [10]:
x=np.array([2,4,6,8])
x=x+1
x

array([3, 5, 7, 9])

In [12]:
x=x-1
x

array([1, 3, 5, 7])

In [13]:
x=x*2
x

array([ 2,  6, 10, 14])

In [14]:
print(x)

[ 2  6 10 14]


In [15]:
x=x/2
x

array([1., 3., 5., 7.])

### Mean Median, Mode, standard deviation

In [17]:
x=np.array([10,20,30,40,50])
np.mean(x)

30.0

In [18]:
np.std(x)

14.142135623730951

In [19]:
np.median(x)

30.0