### Numpy Matrix

In [4]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x
            

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x[0]

array([1, 2, 3])

In [6]:
x[1]

array([4, 5, 6])

In [7]:
x[2]

array([7, 8, 9])

In [8]:
#here x[0],x[1],x[2] are indexing of x i.e 0, 1, 2
# in both the rows the indexing starts from 0,1,2


In [9]:
x[:,1]

array([2, 5, 8])

In [10]:
x[:,2]

array([3, 6, 9])

In [12]:
x[:,0]

array([1, 4, 7])

In [13]:
# here x[:,1],x[:,2],x[:,0] all indicates that infront of : all rows should be present and after comma it is deciding which
# index is needy for desired outcome

### Transpose
* transpose means interchanging of rows and columns

In [15]:
np.transpose(x)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Matrix Multiplication

In [17]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[3,2,1],[6,5,4],[9,7,8]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 7 8]]


In [18]:
x.dot(y)

array([[ 42,  33,  33],
       [ 96,  75,  72],
       [150, 117, 111]])

In [20]:
y.dot(x)

array([[ 18,  24,  30],
       [ 54,  69,  84],
       [ 93, 117, 141]])