### Broadcast
* Rules
** size of each dimension should be same
** size of one of the dimension should be 1.

In [3]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([2,3,4,5])
x+y

array([3, 5, 7, 9])

In [5]:
# here we can add because here we got all equal elements in both the variables
#but if we do the same decreasing one elements in second variables what will happen

In [6]:
y=np.array([2,3,4])
x+y

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [7]:
# as the elements decrease the broadcast error appears here
# 

In [8]:
np.shape(x)

(4,)

In [9]:
np.shape(y)

(3,)

In [10]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [14]:
y=y.reshape((3,1))
y

array([[2],
       [3],
       [4]])

In [13]:
x+y

array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [16]:
# solve 3x4 and 5x6 matrix
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24],
              [25, 26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35, 36],
              [37, 38, 39, 40, 41, 42]])

B = B[:3, :4]
print(B)


[[13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]


In [17]:
B=B.reshape((3,4))

In [18]:
B

array([[13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28]])

In [20]:
B+A

array([[14, 16, 18, 20],
       [24, 26, 28, 30],
       [34, 36, 38, 40]])