### Masking and Boolean operation in Numpy
* Array + condition = boolean array(mask)

In [3]:
import numpy as np
A=10*np.random.random((5,5))-5
A


array([[-3.0317513 ,  4.40525618,  0.11048609, -2.5425067 , -1.13365599],
       [-1.73619859,  1.20787566,  2.44874661,  3.53429189,  4.89491657],
       [ 0.81315335, -1.46839816, -1.12235191,  1.89859109, -2.62024218],
       [-3.94909801,  3.09182749,  1.77192409,  0.18294927, -4.89851778],
       [-3.07427508,  2.3061915 ,  0.56797533,  0.54547997, -4.71517208]])

In [5]:
mask=A>0
mask
#here mask will only decided  the values which are greater than zero to be true and that are not to be false.

array([[False,  True,  True, False, False],
       [False,  True,  True,  True,  True],
       [ True, False, False,  True, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False]])

In [6]:
A[mask]
#it will only print the values of A>0

array([4.40525618, 0.11048609, 1.20787566, 2.44874661, 3.53429189,
       4.89491657, 0.81315335, 1.89859109, 3.09182749, 1.77192409,
       0.18294927, 2.3061915 , 0.56797533, 0.54547997])